=== AlexAnacardo/2324_lmsgi/ud4/10/10.dtd
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT tiempo EMPTY>
<!ELEMENT paso (#PCDATA)>
<!ELEMENT nombreIng (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT instrucciones (paso+)>
<!ELEMENT ingrediente (nombreIng, cantidad?)>
<!ELEMENT receta (nombre,descripcion,tiempo,ingredientes,instrucciones)>
<!ELEMENT pagina (receta+)>
<!ATTLIST receta plato (primero|segundo|postre) #REQUIRED>
<!ATTLIST tiempo preparacion CDATA #REQUIRED>
<!ATTLIST tiempo coccion CDATA #IMPLIED>
<!ATTLIST cantidad unidad (gramos|pizca|mililitros|cucharada|chorro) #IMPLIED>
<!ATTLIST pagina xmlns:xsi CDATA #IMPLIED>
<!ATTLIST pagina xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== AlexAnacardo/2324_lmsgi/ud4/10/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pagina SYSTEM "10.dtd">
<pagina xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="10.xsd">
<receta plato="segundo">
    <nombre>Risotto Milanesa</nombre>
    <descripcion>Plato estrella de la tagliatella</descripcion>
    <tiempo preparacion="20"/>
    <ingredientes>
        <ingrediente>
            <nombreIng>Arroz</nombreIng>
            <cantidad unidad="gramos">500</cantidad>
        </ingrediente>
        <ingrediente>
            <nombreIng>Cebolla mediana</nombreIng>
            <cantidad>1</cantidad>
        </ingrediente>
        <ingrediente>
            <nombreIng>Azafran</nombreIng>
            <cantidad unidad="pizca">1</cantidad>
        </ingrediente>
        <ingrediente>
            <nombreIng>Queso Parmesano</nombreIng>
            <cantidad unidad="gramos">100</cantidad>
        </ingrediente>
        <ingrediente>
            <nombreIng>Mantequilla</nombreIng>
            <cantidad unidad="gramos">100</cantidad>
        </ingrediente>
        <ingrediente>
            <nombreIng>Sal</nombreIng>            
        </ingrediente>
        <ingrediente>
            <nombreIng>Pimienta</nombreIng>        
        </ingrediente>
        <ingrediente>
            <nombreIng>Caldo</nombreIng>
            <cantidad unidad="mililitros">1000</cantidad>
        </ingrediente>
        <ingrediente>
            <nombreIng>Vino blanco</nombreIng>
            <cantidad unidad="chorro">1</cantidad>
        </ingrediente>
    </ingredientes>
    <instrucciones>
        <paso>1-Picamos la cebolla y la pochamos con la mitad de la mantequilla</paso>
        <paso>2-Cuando esté transparente, echamos el azafrán, el vino y dejamos que reduzca</paso>
        <paso>3-A continuación, incorporamos el arroz, lo sofreímos un poco</paso>
        <paso>4- Vamos añadiendo el caldo caliente poco a poco mientras removemos</paso>
        <paso>5- Salpimentamos</paso>
        <paso>6-Cuando esté casi hecho, agregamos el resto de la mantequilla y el queso</paso>
        <paso>7-Servimos enseguida</paso>
    </instrucciones>
</receta>
</pagina>
