=== AlexAnacardo/2324_lmsgi/ud4/04/04.dtd
<!ELEMENT nombreP (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT anyo_nacimiento (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT perfil_linkedin (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT centro (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT puesto (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT anyo_inicio (#PCDATA)>
<!ELEMENT anyo_finalizacion (#PCDATA)>
<!ELEMENT datos (nombreP,apellido+)>
<!ELEMENT residencia (ciudad,pais)>
<!ELEMENT competencia (nombre,nivel)>
<!ELEMENT formacion (titulacion, centro, anyo)>
<!ELEMENT experiencia_profesional (experiencia+)>
<!ELEMENT experiencia (puesto,empresa,anyo_inicio,anyo_finalizacion?)>
<!ELEMENT datos_contacto (telefono,correo?,perfil_linkedin?,descripcion,competencia*,formacion*,experiencia_profesional?)>
<!ELEMENT curriculum (datos,anyo_nacimiento,residencia,datos_contacto)>

=== AlexAnacardo/2324_lmsgi/ud4/04/04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE curriculum SYSTEM "04.dtd">-->
<curriculum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="04.xsd">    
    <datos>
        <nombreP>Alex</nombreP>
        <apellido>Asensio</apellido>
        <apellido>Sanchez</apellido>
    </datos>
    <anyo_nacimiento>2004</anyo_nacimiento>
    <residencia>
        <ciudad>Benavente</ciudad>
        <pais>Espa√±a</pais>
    </residencia>
    <datos_contacto>
        <telefono>123456789</telefono>
        <correo>alexasensio04clase@gmail.com</correo>
        <descripcion>Un makina</descripcion>
        <competencia>
            <nombre>Ingles EOI</nombre>
            <nivel>C1</nivel>
        </competencia>        
        <formacion>
            <titulacion>ESO</titulacion>
            <centro>IES Leon Felipe</centro>
            <anyo>2020</anyo>
        </formacion>
        <formacion>
            <titulacion>Bachillerato</titulacion>
            <centro>IES Leon Felipe</centro>
            <anyo>2022</anyo>
        </formacion>         
    </datos_contacto>
</curriculum>
