=== AlexAnacardo/2324_lmsgi/examen/03/03.dtd
<!ELEMENT servicio (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>  <!--Hay dos elementos llamaos descripcion, en este caso no hay problema en que se llamen igual-->
<!ELEMENT version (#PCDATA)>
<!ELEMENT fecha_actualizacion (#PCDATA)>
<!ELEMENT sistema_operativo (#PCDATA)>
<!ELEMENT memoria_ram (#PCDATA)>
<!ELEMENT espacio_en_disco (#PCDATA)>
<!ELEMENT puerto (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT comando (#PCDATA)>

<!ATTLIST manual codigo CDATA #REQUIRED>
<!ATTLIST memoria_ram medida (Gb) #REQUIRED>
<!ATTLIST espacio_en_disco medida (Gb|Mb|Tb|Pb) #REQUIRED>
<!ATTLIST url pagina (oficial|wiki|doc|repositorio) #REQUIRED>
<!ATTLIST manual xmlns:xsi CDATA #IMPLIED>
<!ATTLIST manual xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

<!ELEMENT puertos_disponibles (puerto+)>
<!ELEMENT requisitos_del_sistema (sistema_operativo,memoria_ram,espacio_en_disco,puertos_disponibles)>
<!ELEMENT otros_datos (url*)>
<!ELEMENT paso (comando,descripcion)>
<!ELEMENT pasos_instalacion (paso+)>
<!ELEMENT manual (servicio,descripcion?,version,fecha_actualizacion,requisitos_del_sistema,otros_datos,pasos_instalacion)>

=== AlexAnacardo/2324_lmsgi/examen/03/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manual SYSTEM "03.dtd">
<manual codigo="MAN001" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="03.xsd">
    <servicio>Servidor Apache</servicio>
    <descripcion>El servidor Apache de codigo abierto, para plataformas Unix, Microsoft Windows, Macintosh y otras,
        Implementa HTTP/1.1 y sitios virtuales
    </descripcion>
    <version>2.40</version>
    <fecha_actualizacion>2024-03-12</fecha_actualizacion>
    <requisitos_del_sistema>
        <sistema_operativo>Linux</sistema_operativo>
        <memoria_ram medida="Gb">2</memoria_ram>
        <espacio_en_disco medida="Gb">100</espacio_en_disco>
        <puertos_disponibles>
            <puerto>80</puerto>
            <puerto>443</puerto>
        </puertos_disponibles>
    </requisitos_del_sistema>
    <otros_datos>
        <url pagina="oficial">https://httpd.apache.org</url>
        <url pagina="wiki">https://es.wikipedia.org/wiki/Servidor_HTTP_Apache</url>
    </otros_datos>
    <pasos_instalacion>
        <paso>
            <comando>sudo apt install apache2</comando>
            <descripcion>Descargar e instalar el paquete apache2</descripcion>
        </paso>
        <paso>
            <comando>sudo service apache2 status</comando>
            <descripcion>Comprobar el estado del servicio</descripcion>
        </paso>
        <paso>
            <comando>sudo ufw allow Apache</comando>
            <descripcion>Abrir el cortafuegos el puerto 80 y 443</descripcion>
        </paso>
    </pasos_instalacion>
</manual>
