=== AlexAnacardo/2324_lmsgi/ud4/03/03V2.dtd
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha EMPTY>
<!ELEMENT hecho (descripcion, fecha)>
<!ELEMENT historia (hecho+)>
<!ATTLIST fecha dia CDATA #REQUIRED>
<!ATTLIST fecha mes (1|2|3|4|5|6|7|8|9|10|11|12) >
<!ATTLIST fecha anyo CDATA "2024" #REQUIRED>
<!ATTLIST historia xmlns:xsi CDATA #IMPLIED>
<!ATTLIST historia xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== AlexAnacardo/2324_lmsgi/ud4/03/03V2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE historia SYSTEM "03V2.dtd">-->
<historia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="03V2.xsd">
    <hecho>
        <descripcion>Se funda Youtube</descripcion>
        <fecha dia="15" mes="1" anyo="2005"/>
    </hecho>
    <hecho>
        <descripcion>Se funda Google</descripcion>
        <fecha dia="4" mes="9" anyo="1998"/>            
    </hecho>
    <hecho>
        <descripcion>Se funda Facebook</descripcion>
        <fecha dia="4" mes="2" anyo="2004"/>            
    </hecho>
</historia>
