=== AlexAnacardo/2324_lmsgi/ud4/01/01.dtd
<!ELEMENT remitente (#PCDATA)>
    <!ELEMENT destinatario (#PCDATA)>
    <!ELEMENT fecha_mensaje (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT mensaje (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>    
    <!ELEMENT fichero (nombre,tipo)>
    <!ELEMENT mail (remitente, destinatario+, fecha_mensaje, asunto?, mensaje, fichero*)>
    <!ATTLIST mail xmlns:xsi CDATA #IMPLIED>
    <!ATTLIST mail xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== AlexAnacardo/2324_lmsgi/ud4/01/01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mail SYSTEM "01.dtd">
<mail xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="01.xsd">
    <remitente>paco@gmail.com</remitente>
    <destinatario>pepe@gmail.com</destinatario>
    <destinatario>martin@gmail.com</destinatario>
    <fecha_mensaje>2024-01-29</fecha_mensaje>    
    <mensaje>Hola</mensaje>
    <fichero>
        <nombre>fichero1</nombre>
        <tipo>image/jpg</tipo>
    </fichero>
    <fichero>
        <nombre>fichero2</nombre>
        <tipo>video/mp4</tipo>
    </fichero>
</mail>
