=== AlexAnacardo/2324_lmsgi/ud4/05/05.dtd
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT contacto (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT contactNo (#PCDATA)>
<!ELEMENT address (city, state, zip)>
<!ELEMENT employee (firstName, lastName, contactNo, email, address)>
<!ELEMENT company (employee+)>

=== AlexAnacardo/2324_lmsgi/ud4/05/05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE company SYSTEM "05.dtd">-->
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="05.xsd">
    <employee>
        <firstName>Juan</firstName>
        <lastName>Sanchez</lastName>
        <contactNo>123456789</contactNo>
        <email>juansanchez@company.com</email>
        <address>
            <city>Bangalore</city>
            <state>Karnataka</state>
            <zip>560212</zip>
        </address>
    </employee>
</company>
